script:
- bash ./scripts/gitpull.sh
- mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  -B clean install --settings "./settings.xml"
after_success:
- java -jar target/reporting-0.1-SNAPSHOT-jar-with-dependencies.jar projects report/data
  -tt true -tc true
- bash ./scripts/gh_pages.sh
env:
  global:
  - ENCRYPTION_LABEL: a99dc3a02e82
  - COMMIT_AUTHOR_EMAIL: malte.heithoff@rwth-aachen.de
before_install:
- openssl aes-256-cbc -K $encrypted_986202362027_key -iv $encrypted_986202362027_iv
  -in github_deploy_key.enc -out github_deploy_key -d
