language: generic
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_986202362027_key 
    -iv $encrypted_986202362027_iv 
    -in scripts/github_deploy_key.enc 
    -out scripts/github_deploy_key 
    -d
  - chmod 600 scripts/github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add scripts/github_deploy_key
script:
- mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  -B clean install --settings "./settings.xml"
- bash ./scripts/gitPullSimple.sh
#- bash ./scripts/gitpull.sh "EmbeddedMontiArc"
#- bash ./scripts/gitpull.sh "MontiSim"
after_success:
- source ./scripts/zipAndMd5Models.sh
- createZip EmbeddedMontiArc
- emaZip="models$md5.zip"
- createZip MontiSim
- msZip="models$md5.zip"
- createGrammarZip EmbeddedMontiArc
- emaGZip="grammars$md5.zip"
- createGrammarZip MontiSim
- msGZip="grammars$md5.zip"
- createGrammarZip MontiCore
- mcGZip="grammars$md5.zip"
- cd target
- ls
- cd ..
- java -jar target/reporting-0.8-SNAPSHOT-jar-with-dependencies.jar EmbeddedMontiArc -tt -tc -zn $emaZip -svg -grammar -gzn $emaGZip
- java -jar target/reporting-0.8-SNAPSHOT-jar-with-dependencies.jar MontiSim -tt -tc -zn $msZip -svg -grammar -gzn $msGZip -m
- java -jar target/reporting-0.8-SNAPSHOT-jar-with-dependencies.jar MontiCore -grammar -gzn mcGZip -m
- bash ./scripts/deploy-zip.sh $emaZip $msZip $emaGZip $msGZip $mcGZip
- bash ./scripts/deploy-gh_pages.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: malte.heithoff@rwth-aachen.de
