before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_986202362027_key 
    -iv $encrypted_986202362027_iv 
    -in scripts/github_deploy_key.enc 
    -out scripts/github_deploy_key 
    -d
  - chmod 600 scripts/github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add scripts/github_deploy_key
script:
- bash ./scripts/gitPullSimple.sh
- rm *.zip
- source ./scripts/zipAndModels.sh
- createZip EmbeddedMontiArc
- emaZip="$md5.zip"
- createZip MontiSim
- msZip="$md5.zip"
- mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  -B clean install --settings "./settings.xml"
after_success:
- java -jar target/reporting-0.1-SNAPSHOT-jar-with-dependencies.jar EmbeddedMontiArc report/data -tt true -tc true -zn $emaZip
- java -jar target/reporting-0.1-SNAPSHOT-jar-with-dependencies.jar MontiSim report/data -tt true -tc true -zn $msZip -m true
- bash ./scripts/deploy-zip.sh
- bash ./scripts/deploy-gh_pages.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: malte.heithoff@rwth-aachen.de